
print(f"{p_l = }")
print(f"{p_s = }")
print(f"{p_circ_0_2 = }")
print(f"{p_collimation_i = }")
print(f"{p_collimation_o = }")
print(f"{p_t_g = }")
print(f"{p_t_r = }")
print(f"{p_lens_rec = }")
print(f"{p_lens_to_cir = }")
print(f"{p_circ_o_3 = }")
print(f"{mix_in_s = }")
print(f"{mix_in_l = }")
print(f"{p_m_o_1 = }")
print(f"{p_m_o_2 = }")
